scripts/UnitTests/Backend.Tests.ps1, scripts/backend.ps1
Use empty hostname for hyperv host and when creating the hyper-v
instance wrapper, try to set the VhdPath property if the instance
exists.
=> Fixed hyper-v backend so that unit tests pass

scripts/lis_hyperv_platform/lisa_run.ps1
On some PS versions: Expand-Archive -InputObject <PSObject> [[-OutputPath] <String>]
[-EntryPath <String[]>
On some PS versions: Expand-Archive [-Path] <String> [[-DestinationPath]
=> Fixed Expand-Archive params

scripts/package_building/build_artifacts.sh
Specify to the make-kpkg the rootcmd flag to fakeroot and not run
make-kpkg inside fakeroot.
Bug fix link: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717807
=> Removed kernel dirty tag

scripts/package_building/build_artifacts.sh
This step is needed in case the repo is in a detached head state.
If the repo is in a detached head state, the checkout to another
branch and the subsequent git pull is not correctly performed.
=> Always force a git checkout to master

scripts/azure_kernel_validation/remove_azure_vm_resources.sh
-to make sure the container that is removed is the right one, the script will use both the the storage account name and the storage account key
=> [azure_boot_test] Boot logs clean method added

scripts/package_building/deps-lis/rpm/perf/lis-perf.spec
-the new version of perf makefile generates a new file that needs to be added in the perf spec file
=> [package_building] Perf spec file updated

Jenkinsfile, linux_pipeline/Jenkinsfile_developer_patch_validation, linux_pipeline/Jenkinsfile_upstream_kernel
All the build names wil have the following format: 
{BUILD_NUMBER}-{KERNEL_PREFIX}-{KERNEL_VERSION}-{KERNEL_TAG}-{BUILD_DATE}
Example: 2-linux-next-4.15.0-611f09f-09022018
=> [jenkinsfile] Build name changed for msft, upstream and dev pipelines

Jenkinsfile, linux_pipeline/Jenkinsfile_upstream_kernel
As there are no more boot logs created during the hyper-v functional
tests, the whole pipeline will fail when trying to archive those
inexistent boot logs.
=> [lisa] Removed archiving inexistent boot logs

scripts/package_building/build_artifacts.sh
Build debian perf without libaudit support by setting
NO_LIBAUDIT=True in Makefile.perf
If libaudit support is enabled, the perf make will fail on certain
kernels with the error:
`arch/x86/include/generated/asm/syscalls_64.c:370:7: error: expected ]
before x32`
=> [package_building] Fix perf package build on debian

linux_pipeline/Jenkinsfile_lis_rpm_hyperv
We will use separe bvt/fvt labels for WS2012 testing to improve the
testing stability.
=> [lis-rpm] Changed validation allocation on WS2012

linux_pipeline/Jenkinsfile_kernel_bisect_controller, scripts/package_building_bisect/build_artifacts_bisect.sh
The tags wouldn't be fetched if the --all flag is not specified, and
we need it.
=> [bisect] Added --all flag to git fetch

linux_pipeline/Jenkinsfile_kernel_bisect_controller
added output message to inform that the checked commit
was not in the expected state
=> [bisect] made the script more verbose

Jenkinsfile, linux_pipeline/Jenkinsfile_upstream_kernel, scripts/lis_hyperv_platform/main.ps1
lisa test results from msft and upstream pipelines are parsed to the database
using lisa-parser.
Also added the upload of the test results to a specific location.
=> [reporting] Added lisa test results parsing to db

scripts/package_building/deps-lis/rpm/perf/lis-perf.spec
Reverts LIS/lis-pipeline#255 because main kernel perf tools will fail to install
=> Revert "[package_building] Fix for perf package building"

scripts/package_building/deps-lis/rpm/perf/lis-perf.spec
Reverts LIS/lis-pipeline#254 because main kernel perf tools will fail to install
=> Revert "[package_building] Added new files for perf build in spec file"

scripts/linux_containers_on_windows/build_opengcs_tools.sh
The Makefile path changed from service/Makefile to Makefile in the
following commit:
https://github.com/Microsoft/opengcs/commit/b837a2b56f0b932e302b653aff78efdc2d13df62#diff-b67911656ef5d18c4ae36cb6741b7965
=> lcow: Fix opengcs makefile path

scripts/package_building/build_artifacts.sh, scripts/package_building_bisect/build_artifacts_bisect.sh
"make rpm" is obsolete now, has been replaced with "make rpm-pkg".
Reference: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=dd5806ede3d71b7577d1d9ec853755709b6b40fa
=> [package_building] Replace `make rpm` with `make rpm-pkg`

scripts/package_building/build_artifacts.sh
The script will default to http if no protocol is specified.
=> package-building: Fallback to http when patch links don't match http/scp

linux_pipeline/Jenkinsfile_container_images, scripts/lcow/Build-OpenGCS.ps1, scripts/lcow/Prepare-Env.ps1, scripts/lcow/Run-LinuxKit.ps1, scripts/lcow/Run-StressTest.ps1
Using a custom compiled rtf for Windows binary that works on hosts with multiple physical CPUs.
Removing Stop preference due to script failure when doing error output.
=> lcow: Fixed linuxkit stage for RS5

scripts/lcow/Run-BinariesCheck.ps1
The latest debian container was unable to update and successfully install the cpio package, so I replaced it with a debian based image with the cpio package installed.
=> lcow: Replace debian container with a preconfigured one

linux_pipeline/Jenkinsfile_container_images, scripts/lcow/Run-LinuxKit.ps1
The linuxkit test should fail if the number of passed tests for the current kernel is lower than the number of  passed tests for the base kernel.
=> lcow: Added linuxkit result comparison

linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation, linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_watcher, scripts/ubuntu_azure_kernel/ubuntu_azure_kernel_watcher.sh
An additional check was added to the watcher: If a kernel is detected, an Azure container will be deployed to check if the kernel can actually be installed.
- If it can be installed, then the validation job will be triggered. 
- If not, the kernel version will remain the old one and the next watcher run (after 4 hours) will retry to install the new kernel again.
Small fixes added too:
- Refactored the watcher: Added more comments and outputs; Remove duplicate code
- Added Premium storage for Azure Storage Perf
- Removed 2 Azure Storage Perf TCs
- Reduced watcher roles (kernel check and retry install) cron to 4 hours.
**LE: Can confirm that the change is having the expected behavior.
A set of azure kernels have been detected, first install failed, at the next run the install was successful …
=> watcher-ubuntu-azure: Added container deploy

linux_pipeline/Jenkinsfile_azure_latest_image, linux_pipeline/Jenkinsfile_kernel_bisect_commit_validator
Because of PR https://github.com/LIS/LISAv2/pull/697,
the parameter -ForceDeleteResources has been replaced by
-ResourceCleanup 'Delete'
=> azure: bisect: fix lisav2 params

linux_pipeline/Jenkinsfile_rhel_kernel_validation, scripts/azure_kernel_validation/azure_templates/rhel_deploy/azuredeploy.json, scripts/rhel_validation/get_kernel_version.ps1, scripts/rhel_validation/prepare_lis_vm.sh, scripts/rhel_validation/validate_rhel_vm.sh
This PR is to extend pipeline-redhat-kernel-lis-validation to detect 7.6 latest errata kernels
=> rhel kernel pipeline: Add support for RHEL 7.6

linux_pipeline/Jenkinsfile_rhel_kernel_validation, scripts/rhel_validation/get_kernel_version.ps1, scripts/rhel_validation/prepare_lis_vm.sh, scripts/rhel_validation/validate_rhel_vm.sh
Current pipeline-redhat-kernel-lis-validation enables only EUS Repo to install the kernel.
So, Enhanced this to detect dynamically list of repos where the kernel is available through kernel package downloadable link and will enable these repos through subscription manger before installing the kernel
=> Support errata kernel download from different Repo

linux_pipeline/Jenkinsfile_azure_latest_image
Build is triggered by watcher, should not be triggered by branch indexing.
=> Azure daily images: disable branch indexing

linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
Because owner = exc.getCauses()[0].getUser() is not serializable, the env variable cannot be set and it fails with java.io.NotSerializableException: hudson.model.User
Adding toString to the user fixes the error.
=> ubuntu_kernel: fix db report with non signed kernel

linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation, linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_watcher
The Ubuntu Azure Kernel watcher will send to the pipeline the full kernel version, so that it can be used for database reporting.
=> ubuntu_kernel: use kernel type and kernel version for db reports

linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
`emailList` remained empty because the wrong variable was used.
=> Ubuntu Azure Kernels: Fix empty mail list for sign-off stage

linux_pipeline/Jenkinsfile_container_images
The tests were disabled per Simon's request, as they always fail on the current pipeline setup.
=> LCOW: Disabled tests

scripts/dpdk/dpdk-email-groovy-text.template
dpdk: added info for latest DPDK test cases, as at the initial template commit , those tests did not exist in LISAv2
=> dpdk: added info for latest DPDK test cases

scripts/rhel_validation/prepare_lis_vm.sh
When installing kernel with yum, it is also updating the dependency packages
Due to which dependency packages are not downloaded with yumdownloader
So changed the logic to download the kernel with dependencies before installing and then upload to the blob
=> Fix for Downloading dependency RPM packages of kernel detected

linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation, scripts/package_building/utils.sh
Before fix, the hostname is too long, getconf HOST_NAME_MAX return 64.
But 'LISAv2-TwoVM1Dep-ubuntuAzuredisco-OU41-637002911910-dependency-vm' is 65.
When inject hostname, VM only accept 64 characters, but in /etc/hosts file, we use above string, this cause test case failed.
···
[LISAv2 Test Results Summary]
Test Run On           : 08/02/2019 05:40:48
VHD Under Test        : ubuntu_19.04_gen1_gen2.vhdx
Initial Kernel Version: 5.0.0-15-generic
Final Kernel Version  : 5.0.0-1013-azure
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:11
ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
--------------------------------------------------------------------------- …
=> Shorten RGIdentifier.

scripts/package_building/build_artifacts.sh, scripts/package_building/deps-lis/rpm/perf/lis-perf.spec
For upstream pipeline, already tested against Linux-next, Linux-stable and MSFT kernel.
=> Fix build issue on CentOS + linux-next.

linux_pipeline/Jenkinsfile_developer_comparison_validation
1. Set the default value of 'FUNCTIONAL_TESTS_CATEGORY' is Functional. For the BVT test category doesn't exist anymore, the default value should be a valid value instead of "BVT".
2. Fix the issue choices parameter have white spaces and indentation. We should provider the user with a good interface. Before fix, some choices parameters have lots of spaces. We should delete them.
=> Fix some issues of Jenkinsfile_developer_comparison_validation

linux_pipeline/Jenkinsfile_dpdk_pipeline, scripts/package_building/check_latest_tags.sh
Updated check_latest_tags.sh script to check DPDK releases that are higher than 17.11, which is no longer supported by Azure.
As this script is run by pipeline, what will changes result into is shown in the screenshot below.
=> check_latest_tags : check updated to current supported versions

linux_pipeline/Jenkinsfile_kernel_bisect_controller
Add Linux-stable to KERNEL_GIT_URL option. So that we can bisect Linux-stable kernel
=> Add linux-stable to KERNEL_GIT_URL option.

linux_pipeline/Jenkinsfile_dpdk_pipeline, scripts/package_building/check_latest_tags.sh
Added hourly check to the check_latest_tags so that the pipeline can check for new tags every hour and we can get results quicker.
```
abmarath@MININT-VQUSADS:~/lis-pipeline/scripts/package_building$ bash ./check_latest_tags.sh --work_dir "~/" --kernel_tree "git://git.dpdk.org/dpdk-stable" --results "./stable_tags.txt" --exclude_versions "False"
+ main --work_dir '~/' --kernel_tree git://git.dpdk.org/dpdk-stable --results ./stable_tags.txt --exclude_versions False
+ EXCLUDE_VERSIONS=True
+ true
+ case "$1" in
+ WORK_DIR='~/'
+ shift 2
+ true
+ case "$1" in
+ KERNEL_TREE=git://git.dpdk.org/dpdk-stable
+ shift 2
+ true
+ case "$1" in
++ readlink -ef ./stable_tags.txt
+ RESULTS_PATH=/home/abmarath/lis-pipeline/scripts/package_building/stable_tags.txt
+ shift 2
+ true
+ case "$1" in
+ …
```
=> check_latest_tags: added hourly check for tags

linux_pipeline/Jenkinsfile_dpdk_pipeline
Confirmed with Jack and SUSE team that "SLES 15 SP1 is the successor to SLES 15".
=> correcting SUSE image name

scripts/package_building/build_artifacts.sh
The KERNEL_COMMIT assignment in debian/rules requires gawk for text
parsing but gawk may not be installed prior to the kernel build. Without
gawk installed, the linux-image-azure package will Depend on an invalid
package name, such as "linux-image-5.4.40-".
Signed-off-by: Tyler Hicks <tyhicks@linux.microsoft.com>
=> gawk is required in debian/rules

scripts/package_building/kernel_metapackages/linux-latest/debian/rules
Include the kernel version string in the filenames of the kernel
metapackages. Debian package archives and debootstrap expect the deb
filenames to be versioned.
With this change, we see the following differences in the filenames of
the metapackage debs:
linux-headers-azure.deb => linux-image-azure_5.4.58-59a59018719e_amd64.deb
linux-image-azure-dbg.deb => linux-headers-azure_5.4.58-59a59018719e_amd64.deb
linux-image-azure.deb => linux-image-azure-dbg_5.4.58-59a59018719e_amd64.deb
Signed-off-by: Tyler Hicks <tyhicks@linux.microsoft.com>
=> package-building: Include the kernel version in the metapackage filename

linux_pipeline/Jenkinsfile_dpdk_pipeline
Removing SUSE SLES-15-sp1 gen1 latest as this image is no longer available.
=> Removing SUSE from DPDK pipeline

linux_pipeline/Jenkinsfile_dpdk_pipeline
DPDK forces the sign off step even if it's just a manual test run. There are probably some scenarios where you would want a signoff step for a manual run, so let's add a variable to optionally disable the signoff step.
=> DPDK Pipeline Signoff optional disable
