LIS/lis-pipeline

- scripts/backend.ps1
- scripts/lis_hyperv_platform/check_kernel.ps1
- scripts/lis_hyperv_platform/config_drive.ps1
- scripts/lis_hyperv_platform/install_kernel.sh
- scripts/lis_hyperv_platform/main.ps1
- scripts/lis_hyperv_platform/setup_env.ps1
- scripts/lis_hyperv_platform/setup_metadata.ps1
- scripts/lis_hyperv_platform/tear_down_env.ps1
LIS/HyperV platform implementation
> LIS/HyperV Platform implemented

- appveyor.yml
On each PR, the Pester tests can be run by the automated CI
appveyor.com
> Added www.appveyor.com integration

- scripts/package_building/build_artifacts.sh
> Revert "[package_building] Adding git depth parameter"

- scripts/package_building/build_artifacts.sh
- scripts/package_building/utils.sh
The parameter is "msft" by default.
> [package_building] Adding parameter for artifacts folder name prefix

- Jenkinsfile
To ease the development and the testing of the pipeline,
each stage can be configured to run or not.
By default, each stage will be run.
> Added conditional when for every stage

- scripts/backend.ps1
- scripts/lis_hyperv_platform/main.ps1
- scripts/lis_hyperv_platform/setup_env.ps1
-we run icaserial to get the log from the namedpipe
> Added initial hyper-v boot log

- Jenkinsfile
[Added] Junit results for azure tests.
[Changed] Reduced number of git fetch for azure automation code. This
was needed because I've seen issues in past that, sometimes git fetch
fails with unexpected error.
> Added JUNIT result parsing for azure tests

- linux_pipeline/Jenkinsfile_upstream_kernel
Reverts LIS/lis-pipeline#114 as the pipeline takes too much and it is still in the development stage
> Revert "[upstream] Set build_artifatcs clean as true by default"

- linux_pipeline/Jenkinsfile_upstream_kernel
> Revert "[upstream] Change upstream pipeline stage names"

- scripts/lis_hyperv_platform/main.ps1
> lisa] Set PS continue on error so lisa can run

- linux_pipeline/Jenkinsfile_developer_patch_validation
- scripts/package_building/build_artifacts.sh
- now users will be able to give patches in the
following format:
user@server:/path/to/patch
> [developer] Added scp option to the developer pipeline

- Jenkinsfile
- linux_pipeline/Jenkinsfile_developer_patch_validation
- linux_pipeline/Jenkinsfile_upstream_kernel
-this option causes the when condition to be evaluated before entering the agent for that stage
> Added beforeAgent=true to every skippable stage in all pipelines

- README.md
Requirements
Jenkins Master Node information
Advanced features
Stages naming
> [readme] Updated  general information in README.md

- linux_pipeline/Jenkinsfile_developer_patch_validation
- now you can pass them as scp://<HOST>:/<FULL PATH>
- also changed the lisa test parameter to choice
- improved description of patches parameter
> [developer] Added full scp patch support + better param descriptions 

- scripts/package_building/build_artifacts.sh
> Revert "[package_building] Pipe make oldconfig output to /dev/null"

- scripts/package_building/build_artifacts.sh
Added packages needed by Makefile.perf
> [package_building] Added required deps to fully build kernel perf tools

- linux_pipeline/Jenkinsfile_upstream_kernel
- scripts/azure_kernel_validation/validate_azure_vm_boot.sh
- scripts/package_building/build_artifacts.sh
- OS_TYPE and OS_VERSION replaced with DISTRO_VERSION
- choice added for LISA_TEST_XML field
- custom_build_tag parameter added in build_artifacts.sh
> [upstream] Updated parameters

- Jenkinsfile
- linux_pipeline/Jenkinsfile_developer_patch_validation
- OS_TYPE and OS_VERSION replaced with DISTRO_VERSION
- CUSTOM_BUILD_TAG added
> Parameters changed for pipelines

- Jenkinsfile
- linux_pipeline/Jenkinsfile_developer_patch_validation
- linux_pipeline/Jenkinsfile_upstream_kernel
- scripts/lis_hyperv_platform/main.ps1
All the dependencies required by lisa can now be copied from the share
> [lisa] Added the copy of TestContent from share

- scripts/linux_containers_on_windows/lcow_pipeline_watcher.sh
Fixes an error in the code syntax and a few small
aesthetic nits.
> [containers] Fix container watcher code

- linux_pipeline/Jenkinsfile_lis_rpm_hyperv
- scripts/lis_hyperv_platform/main-lis-rpm.ps1
- Variable xml for validation stage added
- Param for lisa destination logs added
- Build number removed from vm name
- Delay between deploy runs added
- Validation distro mapping fixed
> [lis-rpm] Support for variable xml and various fixes

- Jenkinsfile
UDP tests will be executed for datapath -
1. SRIOV
2. Synthetic
[This UDP test uses iperf3 tool]
> Azure - Added UDP test cycle

- Jenkinsfile
- linux_pipeline/Jenkinsfile_upstream_kernel
- scripts/azure_kernel_validation/validate_azure_vm_boot.sh
move RG location to WestUS2 for better capacity planning
> change default RG location

- linux_pipeline/Jenkinsfile_lis_rpm_hyperv
RHEL 7.5 added to deploy scenarios and fvt matrix
> [lis-rpm] Added RHEL 7.5 to test matrix

- linux_pipeline/Jenkinsfile_kernel_bisect_controller
now will always pick the first []
> [bisect] Fixed parsing of git bisect output

- Jenkinsfile
- linux_pipeline/Jenkinsfile_lis_rpm_hyperv
This change affects lis-rpm and MSFT pipelines.
> Performance trigger replaced with build job step

- linux_pipeline/Jenkinsfile_lis_rpm_hyperv
Centos 7.5 was added to deploy and bvt testing list
> [lis-rpm] Added Centos 7.5 to test matrix

- linux_pipeline/Jenkinsfile_kernel_bisect_controller
- scripts/package_building_bisect/build_artifacts_bisect.sh
> Revert "[bisect] Cleanup previous git clone of kernel tree"

- linux_pipeline/Jenkinsfile_developer_comparison_validation
- linux_pipeline/Jenkinsfile_developer_patch_validation
- scripts/azure_kernel_validation/main-azure.ps1
- scripts/azure_kernel_validation/main-stress-azure.ps1
This is an addition to the developer patch pipeline and it will provide an Azure VM provision and reboot loop option.
For eg for 100 provisions the reboot loop will do 100 reboots per VM.
> [comparison] Added azure provision stress testing

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
- scripts/ubuntu_azure_kernel/get_ubuntu_azure_kernel_version.ps1
This enables validation for linux-azure and linux-azure-edge kernel on Hyper-V and Azure. The supported distros are Xenial and Bionic
> ubuntu-azure-kernel: Added Jenkins definition for ubuntu azure kernel validation

- scripts/ubuntu_azure_kernel/get_ubuntu_azure_kernel_version.ps1
Invoke-WebRequest didn't work in every case, so we're changing to
curl. Also introducing robocopy for copying files
> ubuntu-azure-kernel: Changed the html download method

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
- scripts/ubuntu_azure_kernel/get_ubuntu_azure_kernel_version.ps1
Using $lastExitCode instead of $? for robocopy exit status
Changed trigger time and label
> ubuntu-azure-kernel: trigger change

- Jenkinsfile
- linux_pipeline/Jenkinsfile_developer_patch_validation
- linux_pipeline/Jenkinsfile_kernel_bisect_commit_validator
- linux_pipeline/Jenkinsfile_kernel_bisect_controller
- linux_pipeline/Jenkinsfile_stable_kernel_trigger
- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
- linux_pipeline/Jenkinsfile_upstream_kernel
Provide choice to latest 16.04 LTS minor release.
> pipelines: update ubuntu choice to 16.04.5

- linux_pipeline/Jenkinsfile_rhel_kernel_validation
- scripts/rhel_validation/check_lis_modules.sh
- scripts/rhel_validation/prepare_lis_vm.sh
- scripts/rhel_validation/validate_rhel_vm.sh
-Added rhel 6.10 in repo check
-The pipeline will log the output of "uname -r" instead of parameter
> rhel_pipeline: Pipeline fixes

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
- scripts/ubuntu_azure_kernel/get_ubuntu_azure_kernel_version.ps1
Ubuntu 14.04 was added to the validation stage.
The watcher was removed from the pipeline since a watcher job was made for this step.
Watcher is also monitoring for proposed azure-edge kernels on all supported LTS releases.
> ubuntu-azure-pipeline: Added trusty in validation stage

- linux_pipeline/Jenkinsfile_developer_comparison_validation
- linux_pipeline/Jenkinsfile_developer_patch_validation
developer_pipeline: complete rework of the pipeline
The pipeline has been rewriten from declarative to programable,
added stress tests for azure, BVT tests for azure and hyperv.
> developer_pipeline: complete rework of the pipeline

- linux_pipeline/Jenkinsfile_container_images
- scripts/lcow/Get-Artifacts.ps1
- scripts/lcow/Prepare-Env.ps1
- scripts/lcow/remote_scripts/run_lkp_tests.sh
- Added mail reporting. The pipeline will send 2 mails, one when a new package is found and one with a summary containing results for each stage executed.
- Added check in the "prepare_env" stage that checks if the required windows features are enabled on the host.
- Added check for a package metadata file that should contain a unique build ID used for PowerBI and DB reporting
- Small Fixes
> LCOW: Pipeline improvements

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_watcher
Added job validation link in the mail stage
> ubuntu-watcher: Changed email message

- scripts/lcow/New-Report.ps1
For several stages the report will include a summary of "Test failed: number out of total tests".
> LCOW: Added mail summary for all stages

- Jenkinsfile
Azure functional test cases were separated from Hyper-V TCs
> msft: Changed Azure functional test matrix

- linux_pipeline/Jenkinsfile_upstream_kernel
> Add post results into DB

- Jenkinsfile
- linux_pipeline/Jenkinsfile_azure_latest_image
- linux_pipeline/Jenkinsfile_kernel_bisect_commit_validator
- linux_pipeline/Jenkinsfile_upstream_kernel
https://github.com/LIS/LISAv2/pull/697 and https://github.com/LIS/LISAv2/pull/737
Below jenkinsfile use stable branch, so no change this time.
linux_pipeline\Jenkinsfile_developer_patch_validation
linux_pipeline\Jenkinsfile_kernel_bisect_commit_validator
> Update parameter for lisav2 change

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
1. Added NVME Azure testing
2. Added GPU Azure testing (Standard_NC24)
3. Reduced performance tests - replaced performance areas with specific
performance tests but with DB insertion
4. Added Hyper-V excluded test that was causing a fail
> ubuntu_pipeline: Improvements

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
1. Changed NVME Azure location run
2. Added 3 excluded tests for HV
> ubuntu_pipeline: Small fixes

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
Changed mail format to default template of detailed test results.
Also fixed NVME location issue and added a few excluded TCs
> ubuntu_pipeline: Changed mail format

- Jenkinsfile
- linux_pipeline/Jenkinsfile_upstream_kernel
NVME pass against azure platform.
> Change size to eastus2 for FVT

- scripts/rhel_validation/check_lis_modules.sh
- scripts/rhel_validation/prepare_lis_vm.sh
Modification to handle the errata kernel installation failure and
appropiately displaying inbox driver when LIS module is not installed.
> rhel_validation: Handle kernel install failure and version check enhancement

- scripts/rhel_validation/check_lis_modules.sh
- scripts/rhel_validation/validate_rhel_vm.sh
Modification to distinguish between RH6 and RH7 from lsb_release command.
> rhel validation: Show new kernel version in the report.

- linux_pipeline/Jenkinsfile_upstream_kernel
> Add BVT for upstream pipeline.

- linux_pipeline/Jenkinsfile_stable_kernel_trigger
Let know any concern. @chvalean
> Send mail for linux-stable.

- linux_pipeline/Jenkinsfile_azure_latest_image
Added:
- email notification after the test run
- new default TC: NET-ADD-NIC-AFTER-PROVISION
- Telemetry flag. This will enable results to be uploaded in database
- Archive artifacts
> azure-latest-image: Added email

- Jenkinsfile
- linux_pipeline/Jenkinsfile_azure_new_vm_size_provision
- linux_pipeline/Jenkinsfile_upstream_kernel
@chvalean For fix pipeline break.
> Update test case name for LISAv2 test name changes

- linux_pipeline/Jenkinsfile_dpdk_pipeline
- scripts/package_building/check_latest_tags.sh
It will run daily and check if there are new tags on the DPDK repo.
If it finds new tags, it will run all the DPDK tests on distros for each
new tag:
Canonical UbuntuServer 16.04-LTS latest
Canonical UbuntuServer 18.04-DAILY-LTS latest
RedHat RHEL 7-RAW latest
RedHat RHEL 7.5 latest
Openlogic CentOS 7.5 latest
SUSE SLES 15 latest
> dpdk: Added pipeline

- linux_pipeline/Jenkinsfile_azure_latest_image
Pipeline was changed from running specific test names to running all test cases by priority. It will run 2 stages - P0 test cases and P1 test cases.
> azure-latest-image: Changed to Priority-based testing

- Jenkinsfile
- linux_pipeline/Jenkinsfile_upstream_kernel
Testing done, let know if you want to me update CBS_Azure_Secrets_File from Jenkins directly or using this PR to let use Azure_Secrets_TESTONLY_File @chvalean
> Update Secrets_File from CBS to global one Azure_Secrets_TESTONLY_File

- Jenkinsfile
- linux_pipeline/Jenkinsfile_upstream_kernel
@chvalean @ader1990 Please hold on review. I will ping you once I done with testing. Thanks!
> Insert test results into database for linux-next, linux-stable and msft

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
The script will now test P0/P1/P2 for Azure and P0/P1 for Hyper-V rather than specific test categories & areas. Retained NVMe stage for Azure and SR-IOV stage for Hyper-V to ensure testing is not affected by env issues.
> ubuntu_pipeline: Changed to priority-based testing

- linux_pipeline/Jenkinsfile_stable_kernel_trigger
- linux_pipeline/Jenkinsfile_upstream_kernel
Done for initial testing, current enable P0 + P1 against upstream pipeline, will extend for P2 for linux stable after stabilize test cases and environment.
> Update upstream pipeline running based on PRIORITY

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
Further improvements:
- Enabled telemetry
- Added extra excluded tests
- SR-IOV test cases will be run with the same VHDs as the other Hyper-V
stages.
> ubuntu-pipeline: Small fixes

- linux_pipeline/Jenkinsfile_stable_kernel_trigger
- linux_pipeline/Jenkinsfile_upstream_kernel
Run migrate case against dedicated slave.
Change sriov slave.
> Changes for migrate and sriov slaves

- Jenkinsfile
- linux_pipeline/Jenkinsfile_developer_patch_validation
- linux_pipeline/Jenkinsfile_kernel_bisect_commit_validator
Remove LIS area, consolidated into CORE area.
For BVT choice, run Priority 0 tests
> Remove BVT and LIS areas

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
Value will like **-ResultDBTestTag 'cosmic_linux-azure-edge_1134'**
For distinguish perf data from ubuntu pipeline.
> Add test tag for ubuntu pipeline.

- Jenkinsfile
- linux_pipeline/Jenkinsfile_upstream_kernel
> Enable msft pipeline based on Priority

- linux_pipeline/Jenkinsfile_azure_latest_image
Excluded P1 Perf tests from Azure daily image testing
> Azure Daily images: Exclude Perf tests

- scripts/package_building/kernel_versions.ini
This reverts commit 84fc1a650f7af5677e8fd77d04dd3ef415b023e5.
> Revert "[build_branches] Updated branches that are built: linux-msft-4.19.y#0d5c4fe"

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_watcher
The pipeline will now wait for 3 days for the owner to sign off the kernel. Different mails will be sent accordingly.
> ubuntu_pipeline: Added sign-off stage

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
- scripts/reporting/report_pipeline_status.py
update a DB table with each pipeline step status information, including start/end date for execution of each stage.
> ubuntu_kernels: add pipeline status reporting

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
- scripts/reporting/report_pipeline_stage_status.py
ubuntu_kernel: added stage state reports
For each stage, before LISAv2 run, it will insert in the database
the stage name, platform and start date.
After LISAv2 finishes, the row will be updated with end date and
tests statusses (pass/skip/abort/error).
> ubuntu_kernel: added stage state reports

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_watcher
* Trigger validation for Azure / Hyper v and Azure performance independently
> Ubuntu Azure Kernel: Trigger stages independently

- linux_pipeline/Jenkinsfile_rhel_kernel_validation
- scripts/rhel_validation/prepare_lis_vm.sh
- scripts/rhel_validation/validate_rhel_vm.sh
This PR is to download the RHEL errata kernel and devel package and uploaded to a storage account.
> Download errata kernel and upload to storage account

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
* Add report into database that the kernel has been picked up for review, ask for confirmation from user.
* Add superseded status, keep true,false values for database insert
* Change kernel sign-off user input to choice parameter 
* Refactor sign-off mail
> Ubuntu Azure kernels: Add review stage and superseded status in DB

- linux_pipeline/Jenkinsfile_dpdk_pipeline
- linux_pipeline/utils/pipeline_utils.groovy
Added DPDK pipeline status reporting plus individual stage reports.
> dpdk: added status reporting

- linux_pipeline/Jenkinsfile_rhel_kernel_validation
- scripts/rhel_validation/prepare_lis_vm.sh
- scripts/rhel_validation/validate_rhel_vm.sh
Currently the downloadable link for AzCopy is hardcoded in the script, so enhanced to read the link from secret file for better maintainability.
> Enhancement for using AzCopy downloadable link from secret file

- linux_pipeline/Jenkinsfile_dpdk_pipeline
Add DPDK source to the stage name
> dpdk: fix stage name

- linux_pipeline/pipeline-lis-rpm-build-azure.groovy
This PR is based on new LIS RPM Build infrastructure create on Azure.
Updated -
1. Added Prerequisite stage
2. Remove hard-coded ip.sh dependency using new stage "Generate Build Files"
> Added new lis-rpm-build pipeline

- linux_pipeline/Jenkinsfile_azure_lis_hotfix_functional
- linux_pipeline/Jenkinsfile_azure_lis_hotfix_performance
This is the new pipeline added for Hotfix functional and performance tests.  In progress testing of this pipeline.
> hotfix: Add new hotfix functional and Performance pipeline

- linux_pipeline/Jenkinsfile_azure_lis_hotfix_pipeline
The pipeline to create a RPM build and test the build for non-compatible errata kernel
> Upstream Hotfix pipeline

- linux_pipeline/Jenkins_pipeline_msft
Not run HV_P2, since too many failures, will enable them once test result is stable.
> Not run HV_P2 and add azure perf

- scripts/lis_hotfix_pipeline/CreateBuildMachines.ps1
- scripts/lis_hotfix_pipeline/Library.psm1
Changes - 
1. Updated the container name as per Simon's suggestion.
2. Updated the command as per powershell change.
> Updated the base VHD repo container + minor fix

- linux_pipeline/Jenkinsfile_lis_rpm_build_azure
- scripts/lis_hotfix_pipeline/lis-build-vm-power-on-off.ps1
This script will turn ON / OFF Build VMs to save the costs.
> Added script to power ON/OFF LIS build VMs

- linux_pipeline/Jenkinsfile_lis_rpm_build_azure
Also removed unnecessary "WithCredentials" block.
> Changed smoke test subscription to "TEST_ONLY"

- linux_pipeline/Jenkinsfile_rhel_kernel_validation
This PR will be merged once Hot-Fix pipeline is fully functional
> Add stage to trigger Hot-Fix pipeline for non-compatible kernels

- linux_pipeline/Jenkins_pipeline_msft
- linux_pipeline/Jenkinsfile_azure_latest_image
- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
- Change email title for msft pipeline, since current email title will be the same for ubuntu + msft kernel and ubuntu + msft debug kernel
- Exclude case INFINIBAND-HPCX-MPI-2VM till it is stable
> Exclude case INFINIBAND-HPCX-MPI-2VM and update email title for msft pipeline.

- scripts/archive/clean_bootdiag_containers.ps1
- scripts/archive/clear_smoke_bvt_resource_groups.ps1
- scripts/archive/common_functions.ps1
- scripts/archive/copy_lkg_vhds_to_safe.ps1
- scripts/archive/copy_packages_to_azure.ps1
- scripts/archive/copy_single_image_container_to_container.ps1
- scripts/archive/create_drone_from_container_vhd.ps1
- scripts/archive/create_vhd_from_uri.ps1
- scripts/archive/create_vhd_from_urn.ps1
- scripts/archive/download_azure_distro_templates.ps1
- scripts/archive/download_single_vm.ps1
- scripts/archive/generalize_azure_vhds.ps1
- scripts/archive/run_borg_azure.ps1
- scripts/archive/run_bvts_on_container.ps1
- scripts/archive/run_command_on_container.ps1
- scripts/archive/run_command_on_machines_in_group.ps1
- scripts/archive/run_single_bvt.ps1
- scripts/archive/start_variants.ps1
- scripts/archive/template/consume.ps1
- scripts/azure_kernel_validation/main-stress-azure.ps1
- scripts/azure_new_vm_size_provision/watcher-new-azure-vm-size.ps1
- scripts/unit_tests/Backend.Tests.ps1
- scripts/utils/powershell/backend.ps1
- scripts/utils/powershell/helpers.psm1
Below files are modified:
modified:   scripts/archive/clean_bootdiag_containers.ps1
modified:   scripts/archive/clear_smoke_bvt_resource_groups.ps1
modified:   scripts/archive/common_functions.ps1
modified:   scripts/archive/copy_lkg_vhds_to_safe.ps1
modified:   scripts/archive/copy_packages_to_azure.ps1
modified:   scripts/archive/copy_single_image_container_to_container.ps1
modified:   scripts/archive/create_drone_from_container_vhd.ps1
modified:   scripts/archive/create_vhd_from_uri.ps1
modified:   scripts/archive/create_vhd_from_urn.ps1
modified:   scripts/archive/download_azure_distro_templates.ps1
modified:   scripts/archive/download_single_vm.ps1
modified:   scripts/archive/generalize_azure_vhds.ps1
modified:   scripts/archive/run_borg_azure.ps1
modified: …
> Converted AzureRm commands to Az

- linux_pipeline/Jenkinsfile_azure_lis_hotfix_pipeline
PR is verified with Job 351, 352
> Hotfix: Modification to use dependency packages while creating VHD

- scripts/package_building/build_artifacts.sh
- scripts/package_building/deps-lis/rpm/lis-daemon.spec
Done for testing, change for https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/tools/hv/Makefile?id=9b543419652917f048310d0863c47c107c26fb0c
> Fix build break for hv daemon

- scripts/package_building/build_artifacts.sh
Change for https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/scripts/package?id=000ec95fbe757401b5da1c9904840085204e5b3d in linux-next
> Change for Makefile rename and path change in linux-next 

- linux_pipeline/Jenkinsfile_kernel_repo_upload
- scripts/kernel_repo_upload/get_kernel_folder.sh
- scripts/kernel_repo_upload/upload_kernel_folder.ps1
> Add upload files into sasurl for linkedin team.

- scripts/package_building/kernel_versions.ini
This reverts commit 68b34e9464306a5af5994b246d59c3af287a6439.
> Revert "[build_branches] Updated branches that are built: linux-msft-4.19.y#91c36d5"

- scripts/package_building/kernel_versions.ini
This reverts commit 4b794178e230f2caa1828ba66a5e7ff97978e461.
> Revert "[build_branches] Updated branches that are built: linux-msft-4.19.y#2fccfd"

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
> Strict if condition.

- linux_pipeline/Jenkinsfile_kernel_repo_upload
- scripts/kernel_repo_upload/upload_kernel_folder.ps1
Test done, will merge it once Skype team confirm.
> Use new repo URL

- linux_pipeline/Jenkinsfile_azure_latest_image_watcher
- scripts/azure_kernel_validation/get_latest_azure_image.sh
pipeline-azure-latest-image/view/change-requests/job/PR-573/14/
pipeline-azure-latest-image/view/change-requests/job/PR-573/13/
> Latest gallery image - add RHEL and CentOS 8

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
- scripts/ubuntu_azure_kernel/ubuntu_azure_kernel_watcher.sh
> Enable testing against ubuntu 19.10 - eoan

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
> Exclude test cases and restrict if condition when specify test location.

- linux_pipeline/Jenkins_pipeline_msft
- linux_pipeline/Jenkinsfile_developer_patch_validation
- linux_pipeline/Jenkinsfile_kernel_bisect_commit_validator
- linux_pipeline/Jenkinsfile_upstream_kernel
> Fix rm path not found issue

- linux_pipeline/Jenkins_pipeline_msft
- linux_pipeline/Jenkinsfile_developer_patch_validation
- linux_pipeline/Jenkinsfile_kernel_bisect_commit_validator
- linux_pipeline/Jenkinsfile_upstream_kernel
Need consider two situations here.
> Fix rm path

- linux_pipeline/Jenkinsfile_dpdk_pipeline
Since this code will run in Jenkins pipeline I have created and attached a simple groovy code to emulate my changes.
Before:
After:
> Jenkinsfile_dpdk_pipeline: Modified tag Validator to ignore prefix "refs/tags/"

- linux_pipeline/Jenkinsfile_azure_latest_image_watcher
> Remove SLES15, ass SLES15 SP1.

- linux_pipeline/Jenkinsfile_azure_latest_image_watcher
- scripts/azure_kernel_validation/get_latest_azure_image.sh
Exact match gallery image version, since found some images got missed.
> Latest gallery image pipeline improvement

- linux_pipeline/Jenkinsfile_dpdk_pipeline
Changing frequency of monitoring DPDK repo from hourly to daily until pipeline is fixed.
> monitor dpdk repo daily

- linux_pipeline/Jenkinsfile_azure_latest_image
> Use managed disk since gen2 only support managed disk.

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
> Fix issue bring in by enable SGX

- linux_pipeline/Jenkinsfile_lis_rpm_hyperv_lisav2
- scripts/lis_hyperv_platform/lis-rpm-hyperv-tests-lisav2.ps1
Pushing the script which is currently used for running lis-rpm hyperv pipeline.
> Groovy script for running lis-rpm hyperv pipeline.

- linux_pipeline/Jenkinsfile_developer_patch_validation
> Devpatch pipeline - Fix for different platforms.

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
- scripts/ubuntu_azure_kernel/ubuntu_azure_kernel_watcher.sh
> Add focal - 20.04.

- scripts/archive/build-lis-daemons-deb.sh
- scripts/package_building/deps-lis/deb/16/preinst
> Revert "Fix hyperv-daemon"

- linux_pipeline/Jenkinsfile_ubuntu_azure_kernel_validation
> Now except for xenial, all other kernel are 5.3 and 5.4 has built error agaisnt DPDK 18.11

- linux_pipeline/Jenkinsfile_dpdk_pipeline
Also Enabled Release candidate testing on DPDK Stable tree.
> Added a new way to check minimum support version

- scripts/package_building/build_artifacts.sh
Before fix:
Will have this error "error: line 17: Illegal char '-' in: Version:  rolling-lts"
After fix:
Build successfully.
> Add fix for kernel version when building kernel

- linux_pipeline/Jenkinsfile_dpdk_pipeline
brackets were unbalanced previously
> fixing a bug with dpdk pipeline
